---
php_packages:
  - php
  - php-bcmath
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-intl
  - php-mbstring
  - php-mysqlnd
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-imagick
  - php-pecl-xdebug
  - php-soap
  - php-xml
  - php-xmlrpc

extension_build_directory: /opt
extension_modules_folder: /usr/lib64/php/modules
